export const POS_TAGS = [
  { value: "ADJ", label: "Прилагательное" },
  { value: "ADP", label: "Предлог" },
  { value: "ADV", label: "Наречие" },
  { value: "AUX", label: "Вспомогательный глагол" },
  { value: "CONJ", label: "Союз" },
  { value: "CCONJ", label: "Сочинительный союз" },
  { value: "DET", label: "Детерминатив" },
  { value: "INTJ", label: "Междометие" },
  { value: "NOUN", label: "Существительное" },
  { value: "NUM", label: "Числительное" },
  { value: "PART", label: "Частица" },
  { value: "PRON", label: "Местоимение" },
  { value: "PROPN", label: "Имя собственное" },
  { value: "PUNCT", label: "Пунктуация" },
  { value: "SCONJ", label: "Подчинительный союз" },
  { value: "SYM", label: "Символ" },
  { value: "VERB", label: "Глагол" },
  { value: "X", label: "Другое" },
];